# CMake generated Testfile for 
# Source directory: /home/runner/work/opengv/opengv
# Build directory: /home/runner/work/opengv/opengv/_codeql_build_dir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_absolute_pose "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_absolute_pose")
set_tests_properties(test_absolute_pose PROPERTIES  WORKING_DIRECTORY "/home/runner/work/opengv/opengv/_codeql_build_dir/bin" _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;208;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_absolute_pose_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_absolute_pose_sac")
set_tests_properties(test_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;214;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_absolute_pose "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_noncentral_absolute_pose")
set_tests_properties(test_noncentral_absolute_pose PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;220;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_absolute_pose_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_noncentral_absolute_pose_sac")
set_tests_properties(test_noncentral_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;226;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_multi_noncentral_absolute_pose_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_multi_noncentral_absolute_pose_sac")
set_tests_properties(test_multi_noncentral_absolute_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;232;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_relative_pose")
set_tests_properties(test_relative_pose PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;238;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_rotationOnly "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_relative_pose_rotationOnly")
set_tests_properties(test_relative_pose_rotationOnly PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;244;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_rotationOnly_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_relative_pose_rotationOnly_sac")
set_tests_properties(test_relative_pose_rotationOnly_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;250;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_relative_pose_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_relative_pose_sac")
set_tests_properties(test_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;256;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_relative_pose "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_noncentral_relative_pose")
set_tests_properties(test_noncentral_relative_pose PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;262;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_noncentral_relative_pose_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_noncentral_relative_pose_sac")
set_tests_properties(test_noncentral_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;268;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_multi_noncentral_relative_pose_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_multi_noncentral_relative_pose_sac")
set_tests_properties(test_multi_noncentral_relative_pose_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;274;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_eigensolver_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_eigensolver_sac")
set_tests_properties(test_eigensolver_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;280;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_triangulation "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_triangulation")
set_tests_properties(test_triangulation PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;286;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_eigensolver "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_eigensolver")
set_tests_properties(test_eigensolver PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;292;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_point_cloud "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_point_cloud")
set_tests_properties(test_point_cloud PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;298;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_point_cloud_sac "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_point_cloud_sac")
set_tests_properties(test_point_cloud_sac PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;304;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_Sturm "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_Sturm")
set_tests_properties(test_Sturm PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;310;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_sqpnp "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_sqpnp")
set_tests_properties(test_sqpnp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;316;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
add_test(test_sqpnp_comparison "/home/runner/work/opengv/opengv/_codeql_build_dir/bin/test_sqpnp_comparison")
set_tests_properties(test_sqpnp_comparison PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/opengv/opengv/CMakeLists.txt;322;add_test;/home/runner/work/opengv/opengv/CMakeLists.txt;0;")
